/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Footer = () => (
  <footer className="footer">
    <style jsx>{`
      .footer {
        background: linear-gradient(
          180deg,
          rgba(65, 109, 43, 0.4) 15.36%,
          #0a0b04 44.76%
        );
        min-height: 68px;
        margin-top: 105px;
        width: 100%;
      }
      @media (max-width: 991px) {
        .footer {
          max-width: 100%;
          margin-top: 40px;
        }
      }
    `}</style>
  </footer>
);

export default Footer;