/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Logo from './Logo';
import Navigation from './Navigation';

const Header = () => (
  <header className="header">
    <Logo />
    <Navigation />
    <style jsx>{`
      .header {
        position: relative;
        align-self: center;
        display: flex;
        gap: 0;
        font-size: 24px;
        color: #000;
        font-weight: 600;
        letter-spacing: -0.48px;
        line-height: 120%;
      }
      @media (max-width: 991px) {
        .header {
          flex-wrap: wrap;
        }
      }
    `}</style>
  </header>
);

export default Header;