/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const ImageSection = () => (
  <section className="image-section">
    <div className="image-container">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/eaa017baaa7ba6b98f2969c33e6d37e37e2b2915c55416dbd0897600cecb5182?apiKey=f395ac786dcf4f09956a3a9acd692f24&"
        alt="Featured content"
        className="featured-image"
        loading="lazy"
      />
      <div className="image-overlay">
        <div className="dot-navigation">
          {[...Array(5)].map((_, index) => (
            <div
              key={index}
              className={`dot ${index === 0 ? 'active' : ''}`}
            />
          ))}
        </div>
      </div>
    </div>
    <style jsx>{`
      .image-section {
        display: flex;
        flex-direction: column;
        mix-blend-mode: darken;
        overflow: hidden;
        position: relative;
        min-height: 600px;
        flex-grow: 1;
        justify-content: center;
        width: 57%;
      }
      .image-container {
        position: relative;
        border-radius: 30px 0 0 30px;
        background: linear-gradient(
          90deg,
          rgba(255, 255, 255, 0.25) 0%,
          #fff 100.69%
        );
        display: flex;
        flex-direction: column;
        align-items: flex-end;
        padding: 80px 60px 26px;
        height: 100%;
      }
      .featured-image {
        position: absolute;
        inset: 0;
        height: 100%;
        width: 100%;
        object-fit: cover;
        object-position: center;
      }
      .image-overlay {
        position: relative;
        z-index: 1;
        margin-top: auto;
      }
      .dot-navigation {
        display: flex;
        gap: 9px;
        margin: 0 96px 26px 0;
      }
      .dot {
        width: 12px;
        height: 12px;
        border-radius: 50%;
        border: 1px solid #000;
        background-color: #fff;
      }
      .dot.active {
        background-color: #8c8c8c;
      }
      @media (max-width: 991px) {
        .image-section {
          width: 100%;
        }
        .image-container {
          max-width: 100%;
          padding: 40px 20px;
        }
        .dot-navigation {
          margin: 0 10px 26px 0;
        }
      }
    `}</style>
  </section>
);

export default ImageSection;