/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './Header';
import MainContent from './MainContent';
import Footer from './Footer';

const LandingPage = () => (
  <div className="landing-page">
    <div className="content-wrapper">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/985fcee019966ba1ba930c7bb388fecacba49807b6c5ace97935f22f43765d70?apiKey=f395ac786dcf4f09956a3a9acd692f24&"
        alt="Background"
        className="background-image"
        loading="lazy"
      />
      <Header />
      <MainContent />
    </div>
    <Footer />
    <style jsx>{`
      .landing-page {
        background-color: #fff;
        display: flex;
        flex-direction: column;
        justify-content: center;
      }
      .content-wrapper {
        display: flex;
        flex-direction: column;
        overflow: hidden;
        position: relative;
        min-height: 1024px;
        width: 100%;
        padding-top: 49px;
      }
      .background-image {
        position: absolute;
        inset: 0;
        height: 100%;
        width: 100%;
        object-fit: cover;
        object-position: center;
      }
      @media (max-width: 991px) {
        .content-wrapper {
          max-width: 100%;
        }
      }
    `}</style>
  </div>
);

export default LandingPage;