/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Logo = () => (
  <img
    src="https://cdn.builder.io/api/v1/image/assets/TEMP/10dc2eee3f5313e5252e082af780e2266a966cdf0394a384879aa9c75ad6be6e?apiKey=f395ac786dcf4f09956a3a9acd692f24&"
    alt="Company Logo"
    className="logo"
    loading="lazy"
  >
    <style jsx>{`
      .logo {
        aspect-ratio: 6.67;
        object-fit: auto;
        object-position: center;
        width: fit-content;
        box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
        flex-grow: 1;
        flex-basis: 0;
      }
      @media (max-width: 991px) {
        .logo {
          max-width: 100%;
        }
      }
    `}</style>
  </img>
);

export default Logo;