/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import ImageSection from './ImageSection';
import TextSection from './TextSection';

const MainContent = () => (
  <main className="main-content">
    <div className="content-wrapper">
      <ImageSection />
      <TextSection />
    </div>
    <style jsx>{`
      .main-content {
        display: flex;
        flex-direction: column;
        position: relative;
        overflow: hidden;
        min-height: 854px;
        margin-top: 43px;
        width: 100%;
        padding-top: 80px;
      }
      .content-wrapper {
        position: relative;
        border-radius: 30px;
        background-color: #fff;
        align-self: center;
        width: 1200px;
        max-width: 100%;
        padding-right: 80px;
        display: flex;
      }
      @media (max-width: 991px) {
        .main-content {
          max-width: 100%;
          margin-top: 40px;
        }
        .content-wrapper {
          padding-right: 20px;
          flex-direction: column;
        }
      }
    `}</style>
  </main>
);

export default MainContent;