/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Navigation = () => {
  const navItems = [
    { label: 'Sobre', active: true },
    { label: 'Contato', active: false },
    { label: 'Orçamentos', active: false },
    { label: 'Logar', active: false },
  ];

  return (
    <nav className="navigation">
      {navItems.map((item, index) => (
        <button
          key={index}
          className={`nav-item ${item.active ? 'active' : ''}`}
        >
          {item.label}
        </button>
      ))}
      <style jsx>{`
        .navigation {
          border-radius: 0 30px 30px 0;
          box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
          background-color: #8c8c8c;
          display: flex;
          gap: 17px;
          flex-grow: 1;
          flex-basis: auto;
          padding: 17px 12px 17px 0;
        }
        @media (max-width: 991px) {
          .navigation {
            flex-wrap: wrap;
          }
        }
        .nav-item {
          font-family: Inter, sans-serif;
          border-radius: 20px;
          border: 1px solid #000;
          background-color: #fff;
          color: #000;
          padding: 13px 29px;
          font-size: 24px;
          font-weight: 600;
          cursor: pointer;
          transition: background-color 0.3s, color 0.3s;
        }
        .nav-item.active {
          background-color: #000;
          color: #fff;
          box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
        }
        @media (max-width: 991px) {
          .nav-item {
            padding: 13px 20px;
          }
        }
      `}</style>
    </nav>
  );
};

export default Navigation;