/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const TextSection = () => (
  <section className="text-section">
    <p className="description">
      wefwefwaefweaf <br />
      weaf <br />
      ewaf <br />
      waef <br />
      ewaf <br />
      wae
    </p>
    <style jsx>{`
      .text-section {
        width: 43%;
        display: flex;
        flex-direction: column;
        justify-content: center;
      }
      .description {
        width: 100%;
        border-radius: 10px;
        box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
        background-color: #fff;
        color: #000;
        letter-spacing: -0.48px;
        padding: 59px 60px 59px 77px;
        font: 600 24px/29px Inter, -apple-system, Roboto, Helvetica, sans-serif;
      }
      @media (max-width: 991px) {
        .text-section {
          width: 100%;
          margin-top: 40px;
        }
        .description {
          padding: 30px 20px;
        }
      }
    `}</style>
  </section>
);

export default TextSection;